apiVersion: v1
kind: Pod
metadata:
  name: busyboxx
  labels:
    app: v1
spec:
  containers:
    - name: busybox
      image: busybox
      ports:
        - containerPort: 9001
      command: ["sleep","3000"]
