apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apa
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: apa
    spec:
      containers:
      - name: apache
        image: httpd:2
        ports:
        - containerPort: 80
