apiVersion: v1
kind: Pod
metadata:
  name: config-vol
spec:
  containers:
  - name: ngx
    image: nginx
    volumeMounts:
    - name: config-volume
      mountPath: /etc/dummy
  volumes:
  - name: config-volume
    configMap:
      name: app-config
