apiVersion: v1
kind: Pod
metadata:
  name: sec-vol
spec:
  containers:
  - name: ngx
    image: nginx
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: db-secret
