apiVersion: v1
kind: Pod
metadata:
  name: ngx-sec-env
spec:
  containers:
  - name: ngx
    image: nginx
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_user
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_PASS    
